### ISSUE TITLE
Community awareness / direction / Leiningen project management

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#100]
I'm not sure yet what peoples thoughts are on ClojureCLR with regards to Leiningen for project management. I think it'd behoove us to try to be as inline as possible with how the JVM side of the Clojure world lives and if done right would make transitioning from the JVM to CLR relatively painless. What I'm scared of is a fragmented approach to development on the CLR that is fundamentally different from that of the JVM. 

I believe currently that Leiningen for project management would present problems for us since vsClojure wants to manage those dependencies itself (right?).

That said, I think this plugin for Leiningen is our bridge so to speak: https://github.com/kumarshantanu/lein-clr

Now I don't know a whole lot yet about lein-clr plugin for Leiningen at the moment. I wonder if it's possible to create a Leiningen plugin to support grabbing dependencies using nuget? Maybe it's already been done?

What are your throughts on a streamlining of the build process for vsClojure projects?

**Comment by speige** [comment]
https://github.com/aaronc/nleiningen is another option that could be
helpful. Aaron Craelius "aaroncraelius at gmail dot com" has also suggested
incorporating leiningen into vsClojure.

I haven't worked with Clojure on the JVM, nor leiningen, so I don't know
what it would take to convert vsClojure to use it or what benefits it would
provide. I should probably play around with leiningen on the JVM so I can
understand it better.

From the little I know, I think it could definitely be useful for grabbing
dependencies (similar to nuGet, or adding references in the VS UI). If we
used leiningen for dependencies, we'd have to add the references to the
.cljproj files after leiningen downloads them.
It could also be helpful for compiling .clj files, which would basically be
a replacement of clojure.compile.exe. However, I think we would still use
MSBuild for the .csproj & .cljproj files, it'd just call leiningen under
the hood.

Other than dependencies & compilation, I'm not sure what other benefits
leiningen would provide.

Part of what we need to question is whether vsClojure is for C# developers
learning ClojureCLR or ClojureJVM developers switching to ClojureCLR. A C#
developer would be more familiar with the visual studio way of doing things
and less with the ClojureJVM way, so they may be annoyed to have to deal
with things like leiningen. However, a ClojureJVM developer would be
annoyed to have to learn Visual Studio's interface.

As much as we don't want to stray from the ClojureJVM way of doing things,
we also don't want to stray from the .Net way of doing things. So, it'll be
tough to determine which compromises to make.

If you want to prototype incorporating leiningen into vsClojure to see how
it works, go for it! :)

**Comment by frankhale** [comment]
Leiningen in my opinion is the defacto standard for Clojure / ClojureScript
project management. It's wonderfully easy to spin up or maintain existing
projects using it. Additionally the community at large are pouring serious
amounts of effort into plugins, templates, etc.. I don't know how much of
or if any real work has been done to ensure that ClojureCLR can play nicely
in that arena. I know there is lein-clr plugin for Leiningen but beyond
that I just don't know at this point. I think overall that it should
probably become the standard project management tool for ClojureCLR as
well. How that all works out and still work well with vsClojure is anyones
guess.

> Other than dependencies & compilation, I'm not sure what other benefits
> leiningen would provide.

One benefit is for ClojureScript compilation. There is a plugin for
Leiningen called cljsbuild and it allows you to spin up the ClojureScript
compiler to build your CLJS files either once or sit and watch and then
recompile when any of the CLJS files change. The configuration for how lein
cljsbuild knows what to do is in the Leiningen project.clj file that
represents the configuration for a particular Clojure project. It's all
rather elegant and pretty simple to work with.

Another benefit is for project template creation. There is a large and
grown selection of project templates in the while already and they are
fairly simple to write.

> As much as we don't want to stray from the ClojureJVM way of doing things,
> we also don't want to stray from the .Net way of doing things.
> So, it'll be tough to determine which compromises to make.

Absolutely correct. This is a tough one. I'll give it some more thought and
if I come up with any ideas I'll let you know.

I think probably for the near future we continue operating as we are now
given the complexity of vsClojure already.

**Comment by frankhale** [comment]
I forgot to comment on https://github.com/aaronc/nleiningen. This
definitely looks interesting but it's gone almost a year without updates.
I'd really be interested in the rationale behind writing a .NET version. If
it was to reduce dependency on the JVM that would make sense but I'm pretty
sure that ClojureScript depends on the JVM ultimately so I don't see it as
a huge benefit if it's to reduce dependencies. It seems like a ton of work
to try to duplicate what the Clojure JVM folks have already done.

**Comment by frankhale** [comment]
I think for the time being and the fact that ClojureCLR is rather niche and the infrastructure isn't as mature (nLeiningen et al) I just go ahead and close this. When the time is right this more streamlined approach to development can be reengaged.
