### ISSUE TITLE
Rebuild succeeds even when compilation fails (see screenshot)

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#109]
Rebuild succeeds even when compilation fails (see status bar at bottom of VS in this screenshot)

![rebuild-succeeded-when-compilation-fails](https://f.cloud.github.com/assets/190154/1739837/e3837e5c-63ac-11e3-8d39-00102bfa5cba.PNG)

**Comment by speige** [comment]
Can you double check that the configuration manager is set to build
your clojure project? There's a bug that causes that to default to
false, so unless you check it, building the solution succeeds, but
building the clojure project fails.

**Comment by frankhale** [comment]
I can't reproduce this problem now. I'm going to close this and if the problem creeps back up I'll reopen.
