### ISSUE TITLE
MoreInfoUrl in source.extension.vsixmanifest

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#117]
Should the following tag be changed to point to this repo?

``` xml
<MoreInfoUrl>https://github.com/speige/vsClojure</MoreInfoUrl>
```

Proposed change

``` xml
<MoreInfoUrl>https://github.com/vsClojure/vsClojure</MoreInfoUrl>
```

**Comment by speige** [comment]
Yes

**Comment by frankhale** [comment]
Cool. I'm going through the code now doing a pseudo code audit. Just trying to wrap my head around the entire code structure.
