### ISSUE TITLE
Microsoft copyright notice on what looks like custom code

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#118]
ClojureExtension.Project - GeneralPropertyPage.cs

Is this needed at the top of GeneralPropertyPage.cs? This code looks to be custom code.

```
/***************************************************************************

Copyright (c) Microsoft Corporation. All rights reserved.
This code is licensed under the Visual Studio SDK license terms.
THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.

***************************************************************************/
```

**Comment by frankhale** [comment]
Also in ClojureProjectFactory.cs, ClojureProjectFileNode.cs, ClojureProjectNode.cs, OAClojureProject.cs, OAClojureProjectFileItem.cs

**Comment by speige** [comment]
I was able to find very similar code in tutorials on MSDN. I'm guessing that's where Jon got them. Microsoft doesn't show any copyright on their MSDN tutorials as their meant as training for developers. There is also little value in these files that could be copyrighted, as it's simple boilerplate. I think it's safe to remove the copyright.
