### ISSUE TITLE
SettingsStore.cs & SettingsStoreProvider.cs (unused code?)

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#119]
ClojureExtension.Project

The SettingsStore.cs and SettingsStoreProvider.cs are not referenced in the code. Are these works in progress that will later be used?

**Comment by speige** [comment]
This code seems like it could be useful. I wonder if it would allow us to save configuration settings, like hotkeys. I'd have to do more research on visual studio extensibility to know for sure (it may be a deprecated way of doing settings).

We have version control, so if you want to delete it, we can resurrect it if we find the need in the future.

**Comment by frankhale** [comment]
Okay.

**Comment by frankhale** [comment]
These will stay until they can be confirmed as not being used. Will reopen when the time comes.
