### ISSUE TITLE
Unused code in ClojureLanguage.cs

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#122]
Project: ClojureExtension.Deployment
Source File: ClojureLanguage.cs

The following functions are not being used at least according to VS 2013 they have 0 references:

```
GetFormatFilterList
GetLanguagePreferences
GetScanner
ParseSource
```

**Comment by frankhale** [comment]
If it's not too much trouble I'd like to remove all unused code within the project and place that aside for a later time if needed. I think this would be beneficial for a house keeping / understanding point of view to get all the unused code out so that we know exactly what we are dealing with and to aid in overall understanding of how to best move forward.

**Comment by speige** [comment]
Go for it

**Comment by frankhale** [comment]
Okay cool!

**Comment by frankhale** [comment]
I know the following aren't being used because their function body is 

``` csharp
throw new NotImplementedException();
```

```
GetScanner
ParseSource
```

**Comment by frankhale** [comment]
As far as the following functions go they may be called indirectly by Visual Studio. VS2013 is reporting 0 references but I believe that is just because it's not referenced by any of the code inside the solution.

```
GetFormatFilterList
GetLanguagePreferences
```

**Comment by speige** [comment]
This is the same issue as ClojureIntellisenseProvider.cs. I was trying to implement it from a tutorial online, but I couldn't get visual studio to call it.

**Comment by frankhale** [comment]
Do you have a link to that tutorial or any good references that you've found?

**Comment by frankhale** [comment]
I've started a wiki page for resources on writing Visual Studio Extensions

[Resources for Writing Visual Studio Extensions](wiki/Resources-for-writing-Visual-Studio-Extensions)

**Comment by frankhale** [comment]
These function calls have to be implemented because they are coming from the inherited abstract class LanguageService.

```
GetScanner
ParseSource
```

Not going to do any more to this ticket. The code stays.
