### ISSUE TITLE
ClojureIntellisenseProvider.cs

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#123]
ClojureExtension.Deployment

Maybe this file is just being stubbed out, I don't know. What I can tell from looking at it is that it's currently not serving any purpose and every function body is throwing a not implemented exception. 

At least for the time being I am making a motion to delete the file.

**Comment by speige** [comment]
I was trying to get that to work a while back, but I couldn't get any of the methods to be called. I think I wasn't registering it correctly. You can delete it.

**Comment by frankhale** [comment]
Okay sure.
