### ISSUE TITLE
Document vsClojure features in the Wiki 

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#139]
vsClojure would be more accessible to new users if there were documentation on each of its features in the Wiki at https://github.com/vsClojure/vsClojure/wiki

**Comment by frankhale** [comment]
Definitely agree on this!

**Comment by frankhale** [comment]
I haven't checked into it but is vsClojure capable of invoking the Clojurescript compiler for CLJS files? I've only ever interacted with Clojurescript using the lein-cljsbuild plugin for leiningen so am not sure how all of the Clojurescript configuration is done or known about within a ClojureCLR project in vsClojure.

**Comment by speige** [comment]
Yes. You can access this feature by right-clicking in the solution explorer of a normal .Net project and adding a ClojureScript.cljs file. Type some ClojureScript code inside the file. As soon as you save the .cljs, it will invoke the compiler & create a code-behind .cljs.js file with the compiled javascript (or with an error description for compiler errors). You should reference the .cljs.js file from your html.

**Comment by frankhale** [comment]
Oh very nice! What happens when you have multiple .cljs files? Are they all compiled and rolled up into a minified JS file or are they separate files?

**Comment by speige** [comment]
Currently they're separate files. It's very minimal/primitive support for ClojureScript. I created a separate ClojureScript Milestone, maybe we can start logging issues/features specific to ClojureScript there.

It might be good to do a brainstorming session. I haven't thought much about what a ClojureScript developer would need. Probably something similar to MindScape Web Workbench for starters (SASS/SCSS/CoffeeScript Compiler).

The ClojureScript editor is currently identical to the regular Clojure editor. So, intellisense/parenthesis highlighting/etc should work. However, the intellisense isn't 100% accurate, because it's running of the ClojureCLR runtime, not the ClojureScript runtime. We may want to come up with an architecture that allows parts of the editors to be shared & parts to be coded separate (maybe as simple as a base class for shared code with 2 subclasses for disparate code).

**Comment by frankhale** [comment]
Another thing that I think would compliment the wiki is having some screencasts that demonstrate various aspects of vsClojure. I don't mind throwing myself into this mix as soon as I get more comfortable with using ClojureCLR and vsClojure. 

I've been playing with OBS which is an open source tool for creating screencasts. It's serious good! 

http://obsproject.com/

**Comment by speige** [comment]
Great Idea! This would definitely help new users acclimate to the environment/plugin more quickly.

**Comment by frankhale** [comment]
Perhaps we can schedule a Google Hangout sometime to discuss development, technology issues (aka, the mountain that is VS extension development paradigm) and general way forward. This can be planned out well in advance as to make sure everyone's schedule is not trampled on and that there is no stress to work it in immediately.

No worries if you don't want to do video. I don't see much intrinsic value in Google hangout video unless there is something necessary to show. I'm just going to do audio and perhaps some screensharing. Google Hangouts On Air are nice because they can live stream and also be saved to YouTube. I've started to play around with them and really dig it!

**Comment by frankhale** [comment]
I think this issue is related to #142 

Is there a way to merge issues?

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
