### ISSUE TITLE
Online marketing of vsClojure & ClojureCLR

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#142]
There is a lot of outdated or missing information about ClojureCLR online. It's hard for CLR/.Net users to find information about ClojureCLR or vsClojure when most Clojure information online is about the JVM.

Ideas to fix this:
Create documentation for ClojureCLR & vsClojure online.
Find key ClojureJVM pages with similar topics & ask the administrators to add links to the CLR pages on the same topics.
Create a GoogleAdWords (hopefully with very inexpensive cost per click) campaign to point to important ClojureCLR & vsClojure pages.
Create YouTube training videos on ClojureCLR/vsClojure

**Comment by frankhale** [comment]
Perhaps down the road a vsClojure or ClojureCLR channel could be created on YouTube for the various screencasts and/or videos.

I just updated the Wiki and put a new section for Documentation / Training and for now there is a link to screencasting software and a call to arms so to speak asking if anyone would like to contribute a screencast of either vsClojure or ClojureCLR.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
