### ISSUE TITLE
Error opening vsClojure source code project within Visual Studio without vsClojure installed

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#145]
NOTE: This is not really a bug. I did not have vsClojure installed when I tried to open the source code for the vsClojure project source code.

We should probably make a note of the dependency of vsClojure upon itself if one wants to do some development of it.

![opening-vsclojure-source-code-error](https://f.cloud.github.com/assets/190154/2247873/d8801d26-9d72-11e3-9793-d089b5a25307.png)

**Comment by frankhale** [comment]
I just noticed that the wiki does not support images like the Issues do. You cannot just drag and drop them in. I'm going to create a new project on my account for screenshots that can be linked to the wiki.

**Comment by speige** [comment]
We could also create a wikiImages directory in the repo & physically commit each image to the repo & link them from the wiki using the relative repo path syntax.

**Comment by frankhale** [comment]
Do we want a wikiImages directory within the source code of this project or outside of it in it's own project?

**Comment by speige** [comment]
Whatever you prefer is fine with me.

**Comment by frankhale** [comment]
Okay. I was thinking a separate project would probably be better since it won't clutter up the source code here.

**Comment by speige** [comment]
Sounds good.

**Comment by speige** [comment]
Do you want to create the repo underneath vsClojure, rather than frankhale?

**Comment by frankhale** [comment]
Yeah that is a much better place for it.

**Comment by frankhale** [comment]
This is okay, I don't mind that I don't have permission. If you don't mind could you create a new project for screenshots and or attachments we'd like to link from the wiki? THANKS!

"You don't appear to have permission to create repositories for this organization. Sorry about that. "

**Comment by speige** [comment]
https://github.com/vsClojure/Documentation

**Comment by frankhale** [comment]
Sweet!!!!! Thank you!

**Comment by frankhale** [comment]
I'm starting to do some stuff with this now. I think one thing that might be beneficial is if in addition to updating the wiki we also take that information and create separate markdown files within this project to allow for that documentation to be preserved in a format that is not stuck in the Github format. I say this because to my knowledge there is no way to "download" or version a wiki. It seems like that data is stuck behind the Github walled garden and you have to go through Github to access it. I could be wrong about that.

**Comment by frankhale** [comment]
Apparently I am wrong based on this nearly 4 year old Github article: https://github.com/blog/699-making-github-more-open-git-backed-wikis

**Comment by frankhale** [comment]
Okay I was able to clone the wiki. I don't see a way to fork it but maybe I'm just missing something at the moment. The repository is just like any other repository and each of the wiki pages are just .md files. I haven't tried it but maybe we can add folders to the wiki repository so that screenshots can be put in. I don't know. Maybe if everything works out the "Documentation" repo can be discarded.

```
C:\Users\Frank\Documents\GitHub> git clone https://github.com/vsClojure/vsClojure.wiki.git
Cloning into 'vsClojure.wiki'...
remote: Counting objects: 131, done.
remote: Compressing objects: 100% (127/127), done.
Receiving objects:  34% (45/131)   eused 0 (delta 0)
Receiving objects: 100% (131/131), 15.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done
C:\Users\Frank\Documents\GitHub>
```

**Comment by speige** [comment]
If we can commit images directly to the wiki repo, that would be ideal. Let me know if you're able to figure it out & if so, I'll delete the documentation repo.

**Comment by frankhale** [comment]
I added a Screenshots folder and a screenshot to the actual wiki repository (not the Documentation repo) and was able to link it to a wiki page.

https://github.com/vsClojure/vsClojure/wiki/Test

**Comment by speige** [comment]
Nice! Can I delete the Documentation repository?

Also, I added a comment about the vsClojure chicken-egg depenendency to the wiki at https://github.com/vsClojure/vsClojure/wiki/Building-from-Source-Code  do we want to close this issue?

**Comment by frankhale** [comment]
Yeah I think we can do what we need with the wiki repository.

**Comment by frankhale** [comment]
This issue is listed in the wiki for building from source code. Closing this issue.

https://github.com/vsClojure/vsClojure/wiki/Building-from-Source-Code
