### ISSUE TITLE
(Need Help) Syncing vsClojure fork

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#146]
I'm having a serious time keeping my fork sync'ed correctly with this repository. I've followed this howto: 

https://help.github.com/articles/syncing-a-fork

However, I am still getting weird stuff happening where my repository is slightly out of sync even though it doesn't report as so and when I try to make pull requests it wants to commit code upstream that has already been committed in the past.

Can anyone offer some tips on how to manage a fork with upstream? I'm spending far too much time with git headaches. I've had to delete my fork so many times due to my non-understanding of how to correctly do this that I'm going insane.

Thanks!

**Comment by Dashue** [comment]
https://github.com/NancyFx/Nancy/wiki/Git-Workflow outlines the workflow. "Handling changes from Upstream/Master" paragraph is what you're looking for

**Comment by frankhale** [comment]
Thank you! I'll give this a shot.

**Comment by frankhale** [comment]
This workflow seems to be working for me. I'm going to close this for now. If there are any other suggestions please feel free to add.
