### ISSUE TITLE
References are treated differently in Clojure projects from within Visual Studio

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#158]
Adding references and viewing reference properties are different between C# and vsClojure projects. Shouldn't they be the same? Maybe there is some additional things that need to be done in the vsClojure Project code

See screenshots:

C# add reference:

![csharp_add_reference](https://f.cloud.github.com/assets/190154/2488007/ed9d8882-b13c-11e3-91e3-5946f89c4014.png)

C# view reference properties:

![csharp_view_reference_properties](https://f.cloud.github.com/assets/190154/2488010/f5a944da-b13c-11e3-9b8d-a67c81c7b699.PNG)

vsClojure add reference:

![vsclojure_add_reference](https://f.cloud.github.com/assets/190154/2488013/fbbe636e-b13c-11e3-9213-d50f29a92cda.png)

vsClojure view reference properties:

![vsclojure_view_reference_properties](https://f.cloud.github.com/assets/190154/2488014/02ebd004-b13d-11e3-8b88-341376d8d5bb.PNG)

**Comment by frankhale** [comment]
I wonder if the references dialog I'm seeing in a C# project is because of an extension I'm using. Hmmm...

**Comment by speige** [comment]
vsClojure appears to be using the old dialog from VS2010. I don't think the dialog you're seeing for c# is from an extension, I think it was introduced with vs2012.

I wonder if we can just change a GUID somewhere in vsClojure to tell it to use the newer dialog?

On a side-note, I'm not sure adding a reference to a clojure project actually does anything useful. I've always added references by using Reflection/LoadAssembly from within the clojure code itself.

**Comment by frankhale** [comment]
Got it! Okay, I was under the impression that if MSBuild was being used then it could use the references from the proj file but then again I'm probably assuming things because I'm so used to csproj files.
