### ISSUE TITLE
Don't believe DLR-License.html needs to be included in the source code

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#159]
I don't think that the DLR-License.html needs to be included in the source code. As I understand it the ClojureCLR compiler uses the DLR. I don't think we are directly using the DLR. Can this be removed?

**Comment by speige** [comment]
I agree

**Comment by frankhale** [comment]
The License.html in the Dependencies folder is also another one I don't think needs to be included.

**Comment by frankhale** [comment]
FYI, I've created a disconnected fork of vsClojure for tearing apart and such. It's named vsClojureSandbox on my Github page. I'll be uploading the code today.
