### ISSUE TITLE
how can run it on VS 2013 Express

### ISSUE THREAD

**Issue by zoowii** [vsClojure/vsClojure#166]
i mostly play on JVM, but today i want to play clojureclr, finding that vsclojure not supported on VS Express

**Comment by frankhale** [comment]
Visual Studio Express does not support 3rd party extensions.

**Comment by frankhale** [comment]
See this article for clarification on why 3rd party extensions are not supported:

http://visualstudiomagazine.com/articles/2014/05/21/no-extensions-for-visual-studio-express.aspx

**Comment by mark4asp** [comment]
I used Visual Studio Professional 2012, not express.

**Comment by frankhale** [comment]
No worries Mark, this particular issue is unrelated to installation problems people are having on full blown Visual Studio. There seems to be some code failing in certain circumstances causing the whole thing to blow up.
