### ISSUE TITLE
vsClojure 1.0.0 creates executables links to Clojure 1.0.0 even when compiling with Clojure 1.2.0

### ISSUE THREAD

**Issue by dvogel** [vsClojure/vsClojure#33]
I modified the skeleton program.clj as such:
    (ns program
      (:gen-class))

```
(defn -main 
  [& args] (print (str args)))
```

I then compiled using the Build->Rebuild Solution menu item. It resulted in a program.exe, as expected. However when I ran it (from the command prompt) I got this error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer 
for 'program' threw an exception. ---> System.IO.FileNotFoundException: Could 
not load file or assembly 'Clojure, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=null' or one of its dependencies. The system cannot find the 
file specified. File name: 'Clojure, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=null' at program..cctor()
```

This is with vsClojure 1.0.0, installed from the VS 2010 online extension gallery.

**Comment by jmis** [comment]
The assembly version being displayed is the version number given to the assembly when it was compiled and has no relation to an actual version of Clojure.

Extensions distributed as a VSIX, such as vsClojure, cannot perform any installation steps other than copying files.  Therefore, you will need to manually register Clojure in such a way that it can be found when running your executable from the command prompt.  Also, vsClojure only supports the running of Clojure code via the Clojure.Main executable included in the 1.2.0 Clojure distribution.

I'm going to close this issue and open an enhancement for implementing the running of Clojure executables from within vsClojure.  The management of Clojure outside of Visual Studio will be left up to the developer for the time being.

**Comment by jmis** [comment]
The latest version of vsClojure supports running executables.  The build process will copy the assembly containing the Clojure semantic model along with that assembly's dependencies to the output directory.  Executing the project's executable from vsClojure will dynamically set the "clojure.load.path" environment variable so that the Clojure libraries can be found.  If you want to run your application outside of vsClojure then you will need to set that same environment variable.

**Comment by Pani83** [comment]
I have set an environmental variable call clojure.load.path with value to clojure-clr foldel, but I still can't run the executable.

Can you help?

Thanks in advance

ps.Great work with vsClojure!!!
