### ISSUE TITLE
No REPL menu in VS2010 SP#1

### ISSUE THREAD

**Issue by mcmarto** [vsClojure/vsClojure#36]
After installing the vsClojure extension through the Extension Manager, I can create Clojure projects fine but cannot see any Clojure REPL in the menus - it does not appear in the "Project" menu nor (apparently) elsewhere. Is this a known issue? 

I am using Visual Studio 2010 and have the recently released Service Pack 1 installed too.

**Comment by jmis** [comment]
You can find the start REPL command by right clicking on your Clojure project in the Solution Explorer.  Let me know if it's not there.

**Comment by mcmarto** [comment]
It wasn't there previously (for me) but I recently had reason to re-install Visual Studio and it seems to be working this time around.
