### ISSUE TITLE
it don't work in vs2010sp1 on win7sp1. but it can work in  vs2010sp1 on win7.

### ISSUE THREAD

**Issue by lincpa** [vsClojure/vsClojure#38]
it don't work in vs2010sp1 on win7sp1.  
it can work in  vs2010sp1 on win7.

**Comment by jmis** [comment]
Make sure that you have both the .NET 3.5 and .NET 4 frameworks installed.  If you do then could you provide more details around the error that you're seeing?

**Comment by lincpa** [comment]
error:
(1) I no find Clojure project Item template after clicked  vs2010 "new-project" Menu. 
(2) I can't open clojure project (creat by vsClojure in vs2010 on win7 both .net3.5sp1 .net4, now update to vs2010sp1 win7sp1  ,run by other pc )
I already have did:
(1) select and install .net3.5.1 in windwos7sp1. (windwos7sp1 only use .net3.5.1, windwos7sp1 can't install net3.5sp1.)   ? .net3.5. 1 =  .net3.5sp1
(2) reinstall .net4.0.
(3) reinstall vs2010.
(4) reinstall vs2010sp1
(5) reinstall vs2010sp1sdk
