### ISSUE TITLE
Update to ClojureCLR version 1.3.

### ISSUE THREAD

**Issue by dmiller** [vsClojure/vsClojure#41]

**Comment by jmis** [comment]
I'm going to include the runtimes as zip files which will be extracted after installation.

**Comment by dmiller** [comment]
Okay.  Need me to do anything on this?

Been looking at other IDEs.  It turns out they are not magic. :)
I'll write up some notes.

On Mon, Jan 23, 2012 at 12:27 PM, jmis <
reply@reply.github.com

**Comment by dmiller** [comment]
Rather than using issues, wikis and a ton of e-mails, willing to try
something new?

https://trello.com/

I don't like most tools, but I'm always looking around.

**Comment by jmis** [comment]
I agree, we should use a collaboration and project management tool that's better than the GitHub issue and comment system.  I toyed with the idea of using the project management tools in TFS.  Although, TFS as a source control system is a step backward when compared to Git.

Would you be able to provide me with a 1.2.0 ClojureCLR build for .NET 4?

**Comment by dmiller** [comment]
I've got some time tomorrow.  Will take care of it in the morning.

https://trello.com/  -- too simple?

I'll look around for something free and online.

**Comment by jmis** [comment]
Yeah, I'm thinking that Trello is too simple.  Maybe I'm being picky, but
I'd like to have a tool that ties project management, collaboration, and
the development process together.  GitHub does this well when compared to
the other free web-based project management tools that I looked at last
night.  I do like having discussions within an issue to link our thought
and design processes directly to code.  However, this doesn't mean that all
of our communication should be done via issues.  What if we created a
discussion group where we can collaborate on project ideas?  Also,
disabling automatic e-mail notifications from GitHub will eliminate spam
when we comment on issues but will make it more difficult to follow along.

**Comment by dmiller** [comment]
I don't mind the e-mail notifications.  I don't get that much traffic at
this e-mail address.

Any reason not to use  http://groups.google.com/group/vsclojure-extension
for our general design/features discussions, and moving to github issues
when a task is decided?

On Tue, Jan 24, 2012 at 1:47 PM, jmis <
reply@reply.github.com

**Comment by jmis** [comment]
That discussion group was originally intended to be for our users to
discuss the extension, get help, suggest features, etc.  Combining project
& development discussion with user discussion may become disorganized.

**Comment by dmiller** [comment]
Re:  Would you be able to provide me with a 1.2.0 ClojureCLR build for .NET
4?

A lot harder than I thought.  1.2.0 was before we revised the build
process.  It also worked against 0.9-vintage DLR, not 1.0.  So I have to
back and find a distribution of the DLR that works, then confirm that I
really can build a net4 release on it.

Working ... .

**Comment by dmiller** [comment]
37signals basecamp?

Or do you just want to create another group on google?

On Tue, Jan 24, 2012 at 2:58 PM, jmis <
reply@reply.github.com

**Comment by dmiller** [comment]
I'm not sure.

I cannot get DLR 0.9 to build under .Net4.

So I'll have to take the CLojureCLR 1.2 sources, reconfigure all projects
to output to .net4, redo all references to DLR DLLs, and then go in and
hack code.  I already know that all internal references to
Microsoft.Scripting.Core have to go, not sure how much else.  I'll keep
playing, but it may be another day due to other time contraints at the
moment.

**Comment by jmis** [comment]
I didn't notice that Basecamp has a free plan.  I'll check it out tonight.
 It looks promising.

**Comment by jmis** [comment]
Yeah, I started down that route last night but stopped.  I figured that you
had a better plan of attack.

On Tue, Jan 24, 2012 at 4:35 PM, David Miller <
reply@reply.github.com

**Comment by dmiller** [comment]
Done.

I uploaded it to the downloads section of the old site.

https://github.com/downloads/richhickey/clojure-clr/clojure-clr-1.2.0-debug-4.0.zip

On Tue, Jan 24, 2012 at 3:44 PM, jmis <
reply@reply.github.com

**Comment by dmiller** [comment]
Other possibilities on the collab front:

https://company.podio.com/   - has free accounts for smaller projects

http://www.goalkeeper.rs/  - has free accounts for smaller projects

Requiring hosting:
http://www.projectpier.org/about-projectpier
http://www.redmine.org/

Podio looks clean.

All look like overkill for two guys trying to have a design discussion and
track some issues.
  :)

**Comment by jmis** [comment]
I didn't get a chance to look at Basecamp last night.  I'll try to take a look at it and the others you mentioned tonight.  Maybe GitHub is good enough for us?

**Comment by dmiller** [comment]
It might be good enough.

We can always use the wiki as a scratchboard.

On Wed, Jan 25, 2012 at 10:18 AM, jmis <
reply@reply.github.com

**Comment by dmiller** [comment]
I may have meant either sketch board or whiteboard, but definitely not
scratchboard. :)
