### ISSUE TITLE
Create a last build on jmis/vsClojure to notify existing users.

### ISSUE THREAD

**Issue by dmiller** [vsClojure/vsClojure#42]
Pop up a notification dialog when the user opens a clproj project/solution.

**Comment by jmis** [comment]
I think we can create a conversion process that will download and install the correct version of vsClojure.

From Microsoft's site:

"Extension Manager recognizes updates by comparing the VSIX manifest of the incoming extension to that of the installed extension. To be recognized as an update, the incoming manifest must have the same ID as the installed one, and a higher Version number. If the Version number is the same or lower, the package cannot be installed. If the ID values do not match, the package that is not yet installed is recognized as a separate extension."

Blog post on how to download and install extensions: http://blog.ninlabs.com/2011/04/auto-update-visual-studio-extensions/

As long as we increment the version number and keep the same VSIX ID then existing users should automatically download our installer.

**Comment by jmis** [comment]
Rough pass at the installer is complete and commited to the vsClojure organization.  I still need to add error handling.

**Comment by jmis** [comment]
The download and installation process was getting too complicated to simply be a throw away.  I trimmed it down to notifying the user of the updated version and offering to uninstall the deprecated version.
