### ISSUE TITLE
Investigate compatibility issues

### ISSUE THREAD

**Issue by dmiller** [vsClojure/vsClojure#44]
Clear existing compatibility isses from the tracker.
Investigate if MSBuild integration caused by VSIX is part of the problem.

**Comment by jmis** [comment]
I installed Windows XP Mode, the latest OS updates, the Visual Studio shell, and vsClojure.  The REPL and build process did not work.  There were no obvious or meaningful error messages.  I found that Clojure CLR 1.2 requires the .NET 3.5 runtime which was not installed with the VS2010 shell.  After installing .NET 3.5, vsClojure worked as expected.  I replied to the user submitted issues to ask them to verify that they have .NET 3.5 installed.

We will need to figure out a way to make .NET 3.5 a requirement when running vsClojure.

**Comment by dmiller** [comment]
That would explain it.  The world moved on.  XP didn't.

**Comment by dmiller** [comment]
It looks like I created only one version of the ClojureCLR 1.2 binary distribution.

For ClojureCLR 1.3, I created binary distributions for .Net 3.5 and .Net 4.0.  Can you include both and detect which to use from the target?

**Comment by jmis** [comment]
Are we able to get a build of 1.2 for .NET 4?  I'm thinking that we should distribute ClojureCLR versions that are compatible with VS2010 out of the box.

**Comment by dmiller** [comment]
Clojure 1.2 will build on .Net 4, no problem.

There is a zip of the 1.2 source under tags.  If one pulls that down and
builds with the right target, one can get the desired assemblies.

I'm on the wrong pc at the moment, won't be able to get on the appropriate
box until after dinner tonight.

-David

On Sat, Jan 21, 2012 at 5:49 PM, jmis <
reply@reply.github.com

**Comment by jmis** [comment]
Close by commit for issue #41.
