### ISSUE TITLE
Configurable Runtime Path

### ISSUE THREAD

**Issue by dmiller** [vsClojure/vsClojure#47]

**Comment by jmis** [comment]
_iandavies1985's changes:_
- [ ] **Removal of the ClojureCLR runtime** - We're still considering our options for ClojureCLR deployment.  We want to continue to ship the runtime with vsClojure until a deployment decision has been made.
- [ ] **Setting of the ClojureCLR runtime path in the project file** - Setting of the runtime path will cause the project file to become machine-specific.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
