### ISSUE TITLE
Would you like support Sharpdevelop? VS2010 is too huge&complicated.

### ISSUE THREAD

**Issue by lincpa** [vsClojure/vsClojure#60]
Would you like support Sharpdevelop?  VS2010 is too huge&complicated.

**Comment by jmis** [comment]
We currently plan to only provide support for Visual Studio.  The core features such as parsing, syntax highlighting, and the REPL, are decoupled enough to be used independently of the vsClojure extension.  I also plan to completely separate these features in to an assembly that a developer could reuse more easily.
