### ISSUE TITLE
Autoformat Code

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#67]
There should be a command from the Edit menu (and with a keyboard shortcut) to AutoFormat a Clojure .clj (or ClojureScript .cljs) code file.

As much as possible, it should use the style guidelines from https://github.com/bbatsov/clojure-style-guide

**Comment by frankhale** [comment]
+1 

I love that style guide, it's helped me out a lot! 

Just as an aside I find myself using the key combo to format my C# code all the time. It's just become one of those things that has to be done! =)

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
