### ISSUE TITLE
External Clojure Library Support

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#70]
Allow searching/downloading libraries from places like http://www.clojure-toolbox.com/ or other places that nLeinengin searches

**Comment by frankhale** [comment]
What about nuget?

**Comment by speige** [comment]
Good idea. Would we want to take all the common libraries & put them in one nuGet package, or make a separate package for each? Would we want the nuGet to include the .clj files or the compiled .dll files? The benefit to the .dll is that non-vsClojure users could take advantage of the libraries. The benefit to the .clj files is the ability to read the source of the library.

If nuGet includes the .clj files, can we prevent non-vsClojure users from seeing the packages?

How will we maintain the packages to keep them up to date with the online distribution? Ideally we'd let the library owner maintain their own distribution so we don't have to keep up with it.

Doesn't leinengin have a way to pull down library dependencies from the web? I wonder what repositories it searches when looking for packages. Maybe we can piggy-back this feature from lein.

**Comment by speige** [comment]
I wonder if we need a seaparate repository for ClojureCLR libraries, because a lot of libraries probably have some java interop. Or, maybe we can make a javaToCLR.clj which has macros to convert java interop to .net?  There may not be an equivalent method for everything, but a lot of stuff could probably translate.

**Comment by frankhale** [comment]
I can address one point now, I'll follow up on the others tomorrow. 

```
Doesn't leinengin have a way to pull down library dependencies from the web? I wonder what repositories it searches when looking for packages. Maybe we can piggy-back this feature from lein.
```

I'm pretty sure it searches Maven and Clojars, maybe others. Once the packages are downloaded it stores them locally. It looks locally for the files and if they don't exist it reaches out on the web to get them.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
