### ISSUE TITLE
REPL loading speed

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#72]
Keep an extra REPL process loaded in the background so when a user requests a new REPL tab, it can be shown immediately.

Consider separating the textboxes for the prompt & results so that prompt can show immediately, even if the runtime is still loading.

**Comment by frankhale** [comment]
nREPL needs to be considered if/when it ever sees the light of day.

**Comment by speige** [comment]
The main cause of the repl loading speed is the fact that the ClojureCLR runtime itself starts up slowly. This is true for all ClojureCLR executables. It's also the reason I have MetaData.clj load in a separate background thread in ClojurePackage.cs. 

Ideally, we'd see if there's anything we can change in ClojureCLR to make it start up faster. In the meantime, I thought we could do a workaround by having it pre-loaded before the user asks for it.

**Comment by frankhale** [comment]
Yeah yeah, no worries. I hear ya! I can't wait for nREPL to be working because that'll mean we can connect to a networked REPL instead of spinning up our own. Eclipse's REPL uses nREPL.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
