### ISSUE TITLE
Add .cljproj option for signing with .snk file for strong-name assembly

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#74]
Possibly use instructions from http://ryanfarley.com/blog/archive/2010/04/23/sign-a-.net-assembly-with-a-strong-name-without-recompiling.aspx & http://www.hackersbasement.com/csharp/post/2009/09/16/Strong-Name-Unsigned-Assemblies.aspx & add to Clojure.Compile.exe or MSBuild Target.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
