### ISSUE TITLE
Unit Test Runner

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#75]
Allow writing of unit tests in Clojure that will run with Microsoft's Unit Test Runner (or NUnit/Resharper/etc runner)

**Comment by frankhale** [comment]
Do you have any ideas for implementing this? Is this just a matter of adding a template or is there something more involved?

**Comment by speige** [comment]
I'm not really sure. I guess it could be as simple as adding a template with gen-class which has the [TestClass] attribute & the [TestInitialize] on the constructor & [TestMethod] on each test. The idea was that clicking Test/Run/AllTests (CTRL+R A  on my box) would run these tests.

I wouldn't be surprised if visual studio does this by loading each .dll compiled in the solution through reflection & looks for these attributes & executes them. We should try it out.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
