### ISSUE TITLE
Update ClojureScript support for Combining/Minifying

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#78]
Combining/Minifying is a simple command-line switch with the Java Clojure compiler, however I'm not sure the best way to turn it on/off in the project when switching from development to production publish mode. If this were msbuild, I could use different debug/release targets. However, this is done by hijacking the text editor save event and adding the compile .js file to the project. Also, if you have multiple .cljs files, it would seem weird for the combined/minified version to be inside a code-behind file because it's actually tied to multiple files.

Consider specifying ClojureCLR/ClojureScript in .cljproj which would compile entire project to .js file (ClojureScript) or to .dll (ClojureCLR)

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
