### ISSUE TITLE
Visual Studio .cljproj incompatible error

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#85]
If you open visual studio by itself & then afterwords open a .sln containing a .cljproj file, it works fine. However, if you open the same .sln file from windows explorer which auto-opens visual studio with the solution open, the .cljproj file gives an incompatible error.

**Comment by frankhale** [comment]
Yep, I can definitely reproduce this. If I load Visual Studio by itself and then go to File->Open->Project/Solution it will open a project correctly. I wonder if (I'm speculating due to lack of experience with Visual Studio extensions) the project type is not completely registered correctly with Visual Studio?

**Comment by speige** [comment]
This was the issue I originally thought you were experiencing with vs2013.

This issue existed with the very first version of vsClojure before I ever
started working on it. I'm sure you're right that it's not registered
correctly, but I'm somewhat new to visual studio extension programming as
well. It may be smart to start from scratch with the latest online tutorial
or template to make a new project type with no actual clojure functionality
& see if the problem goes away. If so, we can do a diff between the two &
see what's different.

Since there's a workaround & it seemed like a hard issue to solve, I've
ignored it for now :(

**Comment by frankhale** [comment]
I like your idea and think that'd be helpful. On another note, do you have any suggestions on how to run the extension and be able to debug it? Is it a matter of running 2 instances of Visual Studio, one with the extension code and one with a Clojure Project and then connect to the an instance running a Clojure project for debugging?

**Comment by speige** [comment]
Normally I open 2 VS instances as you suggested. If my breakpoints aren't
being hit for some reason, I've added MessageBox.Show code all over the
place.

The correct way is to run the deployment project, which should start an
Experimental instance of visual studio. However, I haven't tried it
recently, it seems like it wasn't working.

Part of the problem is that vsClojure requires you to restart visual studio
after it installs, because it creates an environment variable which it
can't function without. If you don't restart, visual studio will have a
cache of the old environment variables. So, you'd almost have to run the
experimental instance & close it & then run it again.

The issue I've logged for this is
https://github.com/vsClojure/vsClojure/issues/76

**Comment by frankhale** [comment]
Okay great, I'm going to play with this and see what I can do. Can I join
the vsClojure community?

**Comment by speige** [comment]
What do you mean by joining the community?

I've set the repo so that anyone can do a push. However, I also created a
"Contributors" team & added you to it.

**Comment by frankhale** [comment]
I've tried setting the Deployment project as the startup project but VS tells me it can't run a library. I've got the Visual Studio SDK installed, do I need to install anything else in order to run it in the "Experimental instance of Visual Studio"? I'm assuming it starts a VS Shell? Perhaps this what you mentioned by it wasn't working. I'll keep digging.

**Comment by frankhale** [comment]
looks like I'm in, I was referring to the vsClojure community that this project is under here on Github. Oops, I used the wrong choice of words, I meant organization.

**Comment by speige** [comment]
I think my memory had failed me. I guess we actually need to create an
integration test & run that. If you create a brand new extension using the
built-in vs template, it should create an integration test that you can
copy from.

**Comment by frankhale** [comment]
Okay, I'm gonna try that.

**Comment by frankhale** [comment]
Yeah that works as you suggested. In this case the actual VSPackage is the runnable project rather than the sub project for Integration Tests. Running that opens up an instance of Visual Studio and integrates the new VSPackage.

**Comment by frankhale** [comment]
I was hoping that by becoming a member of the community that that would allow me some more control over the issues, eg. I could assign myself to some issues or label them but apparently that doesn't appear to be the case. I'll try again.
