### ISSUE TITLE
Create more templates

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#86]
Possible project templates could be:
WPF Application
WCF Service Application

Possible file templates could be:
Class
ASP.NET MVC Model
Interface
Struct
Enum

Investigate possibility of using existing visual studio designers for XAML/WinForm/Aspx and using a clojure file as a code behind. C# does this as a partial class, but a workaround may be needed because .cljproj compiles to separate dll & each piece of a partial class must reside in the same dll.

Example file templates where this would be useful:
wpf code behind
aspx code behind
winform code behind

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
