### ISSUE TITLE
Show Compiler Errors

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#87]
Compile errors from clojure.compile.exe errors should show in error list with the same format as c# compiler & allow double-clicking to move cursor to error line in file.  They currently show in output window.

They show in error list on save, but not on build.

**Comment by frankhale** [comment]
Hmm, I see errors in the Error List window and you can double click them and it goes to the file. However after double clicking to go to the file it makes a selection in  the file that doesn't make sense. The cursor is placed at the offending line which is good.

![vsclojure-compile-errors](https://f.cloud.github.com/assets/190154/1739339/a0381ac6-6399-11e3-8bd9-367f4e7e0c92.PNG)

**Comment by speige** [comment]
The metadata.clj does a mini compile of each s-expression on save. Its not 100% accurate, but is usually at least helpful.

The msbuild task when doing a real compile on the project uses clojure.compile.exe, but puts the errors in the output window instead of the error window.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
