### ISSUE TITLE
Add VS 2013 support

### ISSUE THREAD

**Issue by johnjelinek** [vsClojure/vsClojure#88]
The REPL doesn't work in VS 2013.

**Comment by frankhale** [comment]
I can confirm this. Out of the box vsClojure is broken in Visual Studio 2013 Ultimate. Creating a new console project, right clicking on the program.clj and clicking "Start Clojure Repl" does nothing. There is no visual on what is going wrong it just doesn't do anything. Additionally, compiling of the console project with a freshly installed vsClojure does not work either. There are assumptions being made about the environment and where ClojureCLR is installed that are not correct out of the box.

I downloaded vsClojure from Extensions and Updates on the Tools menu in Visual Studio, version 2.1.4 of vsClojure was downloaded and installed. Perhaps this version is out of date and I should compile and install from the Github repo?

```
Warning 1   Could not resolve this reference. Could not locate the assembly "Clojure.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets 1635    6   Console Application1

Error   2   The command ""\ClojureCLR-1.5.0\Clojure.Compile" -o "Console Application1.exe" -i "program"" exited with code 3.    C:\Users\Frank\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\dcqy1uxq.g5f\Templates\Projects\Console Application\Console Application.cljproj 79  6   Console Application1
```

**Comment by speige** [comment]
This should be fixed in the latest commit. It has also been published to the visual studio gallery. Please try it out and let me know if you have more problems.

**Comment by johnjelinek** [comment]
Quick question, does vsClojure have a dependency on Clojure 1.4.0? Does
this need to be upgraded?

**Comment by frankhale** [comment]
John, the source code has a config file in it that specifically denotes
Clojure 1.5.0. This appears to be something that can be changed outside of
the code but I'm not sure where just yet.

**Comment by speige** [comment]
John,

vsClojure installs to
C:\Users[username]\AppData\Local\Microsoft\VisualStudio[visual
studio version]\Extensions[randomCharacters]

In that folder, there is a runtimes folder which contains the supported
clojure versions.

Originally, the old versions of Clojure were there, but it was hard to
maintain compatability & no one was using the old versions, so I removed
them.

If you right-click the .cljproj file & click properties, you can change the
clojure version. If a folder exists in the \runtimes for the version number
you specified, it will use that when compiling. The .cljproj files are xml
msbuild files that you view in a text editor, you should be able to see how
it compiles by reading that.

I plan on adding 1.6 support soon. For now, if you need a version other
than 1.5, you can create a folder in the \runtimes folder. However, for
older versions, you may have to modify the ClojureCLR binaries or the
.cljproj xml file to make it work.

Devin

**Comment by johnjelinek** [comment]
I just installed the new extension, I'll try it out. Also, note, the syntax highlighting doesn't look good in the dark theme:

![windows_server_2012_r2_datacenter](https://f.cloud.github.com/assets/873610/1716083/ce78b2ea-61bb-11e3-90fa-1950a1992617.png)

**Comment by johnjelinek** [comment]
by the way, is there parens matching in vsClojure? That would be an awesome feature.

**Comment by johnjelinek** [comment]
It would also be pretty sweet if I could do the equivalent of C-x C-e in vsClojure to send the currently highlighted snippet / function to the repl.

**Comment by johnjelinek** [comment]
Note: the REPL is working in VS2013 now :+1:

**Comment by johnjelinek** [comment]
Also, every time my build fails, a dialog popup to debug BootstrapCompile appears. Can this be prevented?

**Comment by frankhale** [comment]
I also use the dark theme so I'll take a look and see what I can do with
the current syntax highlighting of Clojure.

**Comment by frankhale** [comment]
@John, do you mind filing an issue for each of the problems you are
encountering? I'm going to start taking a look to see if I can fix them.

**Comment by johnjelinek** [comment]
@frankhale will do.

**Comment by johnjelinek** [comment]
@frankhale I added my comments as individual issues.

**Comment by frankhale** [comment]
Great thank you!

**Comment by frankhale** [comment]
This issue can probably be closed. vsClojure is working in 2013 now.

**Comment by johnjelinek** [comment]
Can you review #95 and let me know if it's a VS2013 problem? If it's unrelated, then I'll mark this as closed.
