### ISSUE TITLE
Error Logging

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#89]
Add error logging to make researching bug reports easier. That way if a user has an issue we can ask them to send us their log file to help us debug it.

Consider automating the transmission of the log through email or an online web service. When an exception occurs, it could open an error window with the exception details with a button to send the bug report to us.

**Comment by frankhale** [comment]
What are your feelings on using log4net?

http://www.nuget.org/packages/log4net/

**Comment by speige** [comment]
That's what I've always used. I haven't researched alternatives, but it'd probably be my first choice.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
