### ISSUE TITLE
https://gplus.to/vsClojure - SSL error

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#90]
Not sure if anyone else is having this issue but I wanted to follow the link provided in the description of the project but I get an SSL error: 

"A Visual Studio Clojure extension. https://gplus.to/vsClojure"

In Chrome I see:

```
SSL connection error

Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have.

Error code: ERR_SSL_PROTOCOL_ERROR
```

**Comment by speige** [comment]
Oops. It should have been http://gplus.to/clojureCLR

**Comment by frankhale** [comment]
Okay no problem. =)
