### ISSUE TITLE
Send snippet to REPL

### ISSUE THREAD

**Issue by johnjelinek** [vsClojure/vsClojure#93]
I would like to place my cursor at the end of a block in my code and hit a hotkey to send it to the REPL to execute. This is similar to doing C-x C-e in Emacs.

**Comment by frankhale** [comment]
I definitely agree! We definitely need the ability to easily send code to the REPL.

**Comment by speige** [comment]
This feature already exists. If you have an open REPL, and highlight code in a .clj file in the visual studio editor, you can press CTRL+L to send it to the REPL. You can also press ALT+L to send the entire file to the REPL. You can also right click the text & choose the "Send to REPL" option.

However, I think it'd be good to make the shortcut keys configurable. For example, on my box CTRL+L doesn't seem to work (maybe I have it mapped to something else).

Also, if you don't currently have a REPL open, it'd be nice for it to auto-open the REPL for you.

**Comment by frankhale** [comment]
Thank you for the clarification. I'm not trying to intentionally step on toes here and I'm not all that familiar just yet with the current code base. Sometimes I speak out of turn. I'll try to be better about that in the future.

**Comment by speige** [comment]
No worries. Even if a feature exists currently, it may be buggy or not user friendly. We can still log a bug to polish or enhance it.

**Comment by johnjelinek** [comment]
Is there a docs page with a list of hotkeys?

**Comment by frankhale** [comment]
I'm looking at the code now but I haven't found any doc that lists hot keys. This would be a great thing to have in the wiki.

**Comment by frankhale** [comment]
There is a issue open for hotkeys https://github.com/vsClojure/vsClojure/issues/98
