### ISSUE TITLE
HotKey Configuration Page

### ISSUE THREAD

**Issue by speige** [vsClojure/vsClojure#98]
Create a config page that allows viewing/setting HotKeys for each piece of functionality exposed by vsClojure.

**Comment by ecounysis** [comment]
I cloned the repo and have been looking into this issue.

**Comment by ecounysis** [comment]
The more I look at this feature, the more it seems to be duplicating functionality that is already implemented in Visual Studio with the **Tools / Options / Environment / Keyboard** options page. It seems the Visual Studio community already has a preferred way of handling keyboard shortcuts ([MSDN page](http://29g.us/JGjp1y)). Perhaps we could help our users by including tips on how to assign or change keyboard shortcuts. I also have some ideas for how to leverage the already existing infrastructure in the attached image. Thoughts?
![screenshot_022414_111927_pm](https://f.cloud.github.com/assets/132507/2254744/c93eca52-9de4-11e3-9615-3434bedcd431.jpg)

**Comment by speige** [comment]
Eric,

That's a great idea!

If you can hook into the existing shortcut system, that might be a lot
easier.

Devin

On Mon, Feb 24, 2014 at 11:28 PM, Eric Christensen <notifications@github.com

**Comment by ecounysis** [comment]
That's the thing. Those commands are already in the existing system because
they are created by the extension. I think just renaming them so they
include the string "Clojure" will make them easily searchable and
configurable through the VS options page.

**Comment by speige** [comment]
Sorry, I should have looked at the image more closely before I responded.

Good point. Renaming these or making a schema would make them much easier to find.

Can you test if changing the keys for a clojure shortcut in this menu works correctly? Specifically, can you use the new keystroke to perform the command? If you restart visual studio, do these settings persist?

Also, maybe we should look through all the features in vsClojure to see which commands don't have a shortcut listed in this menu. If a specific command would benefit from having a shortcut keystroke, maybe we can create shortcut keys for them.

**Comment by ecounysis** [comment]
They are all there (even the ones that vsClojure does not have HotKeys for)
and can be changed to whatever. They persist in VS when changed and affect
all editing contexts. We should probably add a new context (where it says
"Use new shortcut in:") so the keybindings for vsClojure are not applied
througout Visual Studio.

For example, I changed my
_Editor.ContextMenus.CodeWindow.LoadSelectedTextIntoRepl_ to Ctrl+X,Ctrl+E
(similar to emacs) from Ctrl+L (assigned by vsClojure), and that prevented
me from cutting with Ctrl+X even though Ctrl+X was still assigned to
the *Edit.Cut
*command.

**Comment by speige** [comment]
I agree, we should figure out how to make a separate context for vsClojure. We don't want vsClojure hotkeys to override c# editor hotkeys. Like you mentioned, the "Use new shortcut in: Global". If you change the dropdown, it has "text editor" as an option. I wonder if we could create a "Clojure Editor" setting somehow? It seems plausible, because there are separate "HTML Editor" & "XML Editor" setting apart from the normal "Text Editor".

I think you're right, all important vsClojure features may be in this list already. I assumed that some features might be only available through a right-click menu. For example, you start a new REPL by right-clicking a project in the solution explorer. However, it's right there in your screenshot, even though vsClojure didn't give it a default hotkey!

I was able to successful assign a hotkey to starting a REPL & it worked. When I right-click the solution, it says "Start Clojure Repl", but it doesn't show my hotkey. It'd be nice if the text changed to reflect the assigned hotkey.

Maybe we should go through the list of vsClojure commands & assign a default hotkey in the vsClojure code.

**Comment by ecounysis** [comment]
Yes. That sounds good. I'll create a new "Clojure Editor" or "Clojure
Buffer" context so these hotkeys only work in that context. Though some of
them may need a broader scope, since starting a clojure REPL (for example)
will not always be done from a Clojure file. In fact I could see opening
one up while developing in C# just to dynamically work with ideas in a REPL.

**Comment by frankhale** [comment]
Will reopen once this becomes a priority
